/**
 * Content-type registry for the Optimizely CMS SDK.
 *
 * The SDK generates GraphQL queries (and the experience `_IComponent`
 * composition fragments) from these definitions, so each type's `key` and
 * property keys must match the content types in the CMS exactly. They mirror
 * the content created via the `cms` CLI (scratchpad/cms/gen.py).
 *
 * Components must declare `compositionBehaviors` (length > 0) or the SDK's
 * `isExperienceComponent` check drops them from the composition fragment and
 * their fields never resolve inside an experience.
 *
 * Registration is idempotent and happens as a side effect of importing this
 * module (see `initContentTypeRegistry` below); import it once from the loaders.
 */
import { BlankExperienceContentType, contentType, initContentTypeRegistry } from "@optimizely/cms-sdk"

/** A link list, as used by Hero / Card / CallToAction. */
const links = {
  type: "array",
  items: { type: "link" },
} as const

export const HeroContentType = contentType({
  key: "Hero",
  baseType: "_component",
  displayName: "Hero",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Heading: { type: "string" },
    SubHeading: { type: "string" },
    Body: { type: "richText" },
    Image: { type: "contentReference" },
    Links: links,
  },
})

export const CardContentType = contentType({
  key: "Card",
  baseType: "_component",
  displayName: "Card",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Heading: { type: "string" },
    SubHeading: { type: "string" },
    Body: { type: "richText" },
    Asset: { type: "contentReference" },
    Links: links,
  },
})

export const CollapseContentType = contentType({
  key: "Collapse",
  baseType: "_component",
  displayName: "Collapse",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Heading: { type: "string" },
    Body: { type: "richText" },
  },
})

export const CallToActionContentType = contentType({
  key: "CallToAction",
  baseType: "_component",
  displayName: "Call to Action",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Links: links,
  },
})

export const ParagraphContentType = contentType({
  key: "Paragraph",
  baseType: "_component",
  displayName: "Paragraph",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Text: { type: "richText" },
  },
})

export const TextContentType = contentType({
  key: "Text",
  baseType: "_component",
  displayName: "Text",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Content: { type: "string" },
  },
})

export const ImageContentType = contentType({
  key: "Image",
  baseType: "_component",
  displayName: "Image",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    AltText: { type: "string" },
    Image: { type: "contentReference" },
  },
})

export const ArticleListContentType = contentType({
  key: "ArticleList",
  baseType: "_component",
  displayName: "Article List",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Title: { type: "string" },
    NumberOfArticles: { type: "integer" },
  },
})

export const ArticlePageContentType = contentType({
  key: "ArticlePage",
  baseType: "_page",
  displayName: "Article Page",
  properties: {
    Heading: { type: "string" },
    SubHeading: { type: "string" },
    Author: { type: "string" },
    AuthorEmail: { type: "string" },
    Body: { type: "richText" },
    PromoImage: { type: "contentReference" },
  },
})

// --- axiom_ design-import content types -----------------------------------
// Generated by the design processor (one per used base block, `axiom_`-keyed,
// flattened/inferred fields). Registered so the SDK's composition query fetches
// their fields; dispatch.tsx maps `axiom_<Block>` → the base block component and
// realigns the field names/shapes. NOTE: these are design-specific — ideally
// generated / registered app-side rather than baked into the generic plugin.
const stringList = { type: "array", items: { type: "string" } } as const

export const AxiomHeroContentType = contentType({
  key: "axiom_Hero",
  baseType: "_component",
  displayName: "Axiom Hero",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Eyebrow: { type: "string" },
    Heading: { type: "string" },
    SubHeading: { type: "string" },
    Links: links,
    Image: { type: "contentReference" },
  },
})

export const AxiomCardContentType = contentType({
  key: "axiom_Card",
  baseType: "_component",
  displayName: "Axiom Card",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    icon: { type: "string" },
    Heading: { type: "string" },
    Body: { type: "string" },
    Links: stringList,
    SubHeading: { type: "string" },
  },
})

export const AxiomCollapseContentType = contentType({
  key: "axiom_Collapse",
  baseType: "_component",
  displayName: "Axiom Collapse",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Heading: { type: "string" },
    Body: { type: "string" },
  },
})

export const AxiomCallToActionContentType = contentType({
  key: "axiom_CallToAction",
  baseType: "_component",
  displayName: "Axiom Call to action",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Heading: { type: "string" },
    SubHeading: { type: "string" },
    Links: links,
  },
})

export const AxiomParagraphContentType = contentType({
  key: "axiom_Paragraph",
  baseType: "_component",
  displayName: "Axiom Paragraph",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Eyebrow: { type: "string" },
    Text_html: { type: "richText" },
    Heading: { type: "string" },
    Callout_value: { type: "string" },
    Callout_label: { type: "string" },
  },
})

export const AxiomTextContentType = contentType({
  key: "axiom_Text",
  baseType: "_component",
  displayName: "Axiom Text",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Content: stringList,
  },
})

export const AxiomImageContentType = contentType({
  key: "axiom_Image",
  baseType: "_component",
  displayName: "Axiom Image",
  compositionBehaviors: ["elementEnabled"],
  properties: {
    Image: { type: "contentReference" },
  },
})

/** Every content type the site renders, registered once for query generation. */
export const CONTENT_TYPES = [
  BlankExperienceContentType,
  HeroContentType,
  CardContentType,
  CollapseContentType,
  CallToActionContentType,
  ParagraphContentType,
  TextContentType,
  ImageContentType,
  ArticleListContentType,
  ArticlePageContentType,
  AxiomHeroContentType,
  AxiomCardContentType,
  AxiomCollapseContentType,
  AxiomCallToActionContentType,
  AxiomParagraphContentType,
  AxiomTextContentType,
  AxiomImageContentType,
]

initContentTypeRegistry(CONTENT_TYPES)
